In [97]:
import pandas as pd

In [98]:
marks = {
    "obj":{
        "1": [9, 8, 10, 7, 10, 8, 4, 4, 5,5, 8],
        "2": [4, 3, 4, 3, 4, 6, 4, 3, 1, 6, 6],
        "3": [8, 7, 5, 7, 7, 7, 8, 8, 6, 8, 7],
        "4": [8, 7, 8, 5, 7, 9, 9, 9, 8, 7, 8 ],
        "5" : [4, 3, 3, 3, 4, 3, 4, 4, 4, 3, 3],
        "6": [5, 5, 4, 5, 4, 4, 4, 4, 4, 4, 4]
        },
    
    "subj": {
        
        "1": [7.5, 7, 7, 5.5, 6.5, 7.5, 7.5, 7.5, 8.5, 7, 6],
        "2": [5, 5, 5.5, 2.5, 4, 5, 5, 4, 5, 5, 5],
        "3": [7.5, 6, 6.5, 7, 7.5, 7.5, 3, 6, 5, 4.5, 5.5],
        "4": [8, 6, 5.5, 5, 6.5, 6.5, 7, 6, 2.5, 3.5, 3.5],
        "5" : [8, 6, 8, 6.5, 7.5, 7, 6, 6, 6.5, 6, 8],
        "6": [4.5, 3.5, 4.5, 3.5, 4, 4.5, 4, 4, 4, 3.5, 4]
        
    }
    
}

In [99]:
import numpy as np
obj = np.array(list(marks["obj"].values())).T
subj = np.array(list(marks["subj"].values())).T

In [100]:
obj.shape, subj.shape

((11, 6), (11, 6))

In [101]:
obj_wt =  np.array([10, 10, 8, 12, 5, 5])
obj_wt[:5]+=obj_wt[5]

In [102]:
obj_wt

array([15, 15, 13, 17, 10,  5])

In [103]:
subj[:, :5]+=subj[:, 5:6]

In [104]:
subj

array([[12. ,  9.5, 12. , 12.5, 12.5,  4.5],
       [10.5,  8.5,  9.5,  9.5,  9.5,  3.5],
       [11.5, 10. , 11. , 10. , 12.5,  4.5],
       [ 9. ,  6. , 10.5,  8.5, 10. ,  3.5],
       [10.5,  8. , 11.5, 10.5, 11.5,  4. ],
       [12. ,  9.5, 12. , 11. , 11.5,  4.5],
       [11.5,  9. ,  7. , 11. , 10. ,  4. ],
       [11.5,  8. , 10. , 10. , 10. ,  4. ],
       [12.5,  9. ,  9. ,  6.5, 10.5,  4. ],
       [10.5,  8.5,  8. ,  7. ,  9.5,  3.5],
       [10. ,  9. ,  9.5,  7.5, 12. ,  4. ]])

In [105]:
obj[:, :5]+=obj[:, 5:6]

In [106]:
obj

array([[14,  9, 13, 13,  9,  5],
       [13,  8, 12, 12,  8,  5],
       [14,  8,  9, 12,  7,  4],
       [12,  8, 12, 10,  8,  5],
       [14,  8, 11, 11,  8,  4],
       [12, 10, 11, 13,  7,  4],
       [ 8,  8, 12, 13,  8,  4],
       [ 8,  7, 12, 13,  8,  4],
       [ 9,  5, 10, 12,  8,  4],
       [ 9, 10, 12, 11,  7,  4],
       [12, 10, 11, 12,  7,  4]])

In [107]:
normalized_obj = obj/obj_wt

In [108]:
normalized_sub = subj/15

In [109]:
result = (normalized_obj + normalized_sub) /2 

In [64]:
r = result[:, :5] > 0.6 

In [87]:
result_a = np.empty_like(result[:, :5], dtype='<U4')

In [90]:
result_a[r] = "pass"
result_a[~r] = 'fail'

In [92]:
result = pd.DataFrame(result_a, columns=[f"Unit-{i}" for i in range(1, 6)])

In [95]:
result.to_csv('result.csv')

In [96]:
result

Unit-1 Unit-2 Unit-3 Unit-4 Unit-5
0    pass   pass   pass   pass   pass
1    pass   fail   pass   pass   pass
2    pass   fail   pass   pass   pass
3    pass   fail   pass   fail   pass
4    pass   fail   pass   pass   pass
5    pass   pass   pass   pass   pass
6    pass   fail   pass   pass   pass
7    pass   fail   pass   pass   pass
8    pass   fail   pass   fail   pass
9    pass   pass   pass   fail   pass
10   pass   pass   pass   pass   pass

In [114]:
percentage = pd.DataFrame(result[:, :5]*100, columns=[f"Unit-{i}" for i in range(1, 6)])

In [115]:
percentage.to_csv('percentage.csv')